/**
 * WhatsApp Cloud APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface MarkMessageAsReadRequest {
  /** Messaging service used for the request. Use 'whatsapp'. */
  messagingProduct: string;
  /** A message's status. You can use this field to mark a message as read. */
  status: string;
  /** Id of the incoming message. */
  messageId: string;
}

export const markMessageAsReadRequestSchema: Schema<MarkMessageAsReadRequest> = object(
  {
    messagingProduct: ['messaging_product', string()],
    status: ['status', string()],
    messageId: ['message_id', string()],
  }
);
